# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [2]:
# Tenebroso, Jan Florenz
# Casiple, Cyc

import numpy as np

#### 2. Print the numpy version

In [3]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [26]:
import numpy as np

arr = np.empty((5))

print(arr)

[0.00000000e+000 1.00367638e-311 1.00367638e-311 1.00367638e-311
 1.04827398e+223]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [27]:
import numpy as np

arr = np.empty((15))
arr[6] = 1
print(arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [77]:
import numpy as np
from numpy import random

arr = random.randint(15, size=(4, 4))

print(arr)

[[ 5  7 11  8]
 [ 2 12  8  4]
 [ 5  8 13  8]
 [11 11 12  9]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [329]:
import numpy as np


arr = np.array([1, 2, 4, 0, 4, 0])

search = np.where(arr == 0)

print(search)

(array([3, 5]),)


#### 7. Create a 4x4x4 array with random values

In [11]:
import numpy as np
from numpy import random

arr = random.randint(11, size=(4, 4, 4))

print(arr)

[[[ 5  5  2  6]
  [ 8 10  2  0]
  [ 9  5  2  8]
  [ 5  8 10  3]]

 [[ 4  2  6  6]
  [ 3  4  8  8]
  [ 7  7  2  4]
  [ 0  2  9  1]]

 [[ 0  4  4  2]
  [ 0  7  3  2]
  [10  6  1  6]
  [ 9  1  6  9]]

 [[ 4  7  4  1]
  [10  4  9 10]
  [ 0  4 10 10]
  [ 5  1  4  1]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [20]:
import numpy as np
from numpy import random

arr = random.randint(100, size=(15, 15))
max = arr.max()
min = arr.min()
print(min)
print(max)

0
99


#### 9. Create a random array of size 25 and find the mean value

In [34]:
import numpy as np
from numpy import random

arr = random.randint(100, size=(25)) 
storage = 0
for x in arr:
    storage += x
    
storage = storage / 25
print(storage)   

55.0


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [35]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

print(arr1)
print(arr2)

[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [36]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

print(np.add(arr1, arr2))

[ 3 18 15]


10.2 What is the result of *a - b*?

In [39]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

print(np.subtract(arr1, arr2))

[  1 -10   3]


10.3 What is the result of *a × b*?

In [40]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

print(np.multiply(arr1, arr2))

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [41]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

print(np.divide(arr1, arr2))

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [42]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [59]:


import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

filter_arr = arr % 50 == 0

newarr = arr[filter_arr]
print(newarr)

[50]


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [61]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

newarr = arr[1]
print(newarr)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [89]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

newarr = arr[0:3, 2]
print(newarr)


print()

[30 60 90]



4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [93]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

newarr = arr[1:3, (1,2)]
print(newarr)


print()

[[50 60]
 [80 90]]



##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [95]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [96]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

newarr = arr[1:3, (1,2)]
print(newarr)


print()

[[ 6  7]
 [10 11]]



3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [97]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

newarr = arr[0:1, (0,2)]
print(newarr)


print()

[[1 3]]



4. Write code to reverse the order of rows in the matrix

In [156]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


reversed_arr = np.flipud(arr)

print(reversed_arr)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [158]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

newarr = arr[0:3, (2,3)]
print(newarr)


print()

[[ 3  4]
 [ 7  8]
 [11 12]]



##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [ ]:
import numpy as np

arr1 = np.array([11,7,33])
arr2 = np.array([44,5,18])

2. Write code to join arr1 and arr2 into a single 1D array.

In [1]:
import numpy as np

arr1 = np.array([11,7,33])
arr2 = np.array([44,5,18])

arr = np.concatenate((arr1, arr2))

print(arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [3]:
import numpy as np

arr1 = np.array([11,7,33])
arr2 = np.array([44,5,18])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[11 44]
 [ 7  5]
 [33 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [12]:
import numpy as np

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])


print(arr1, arr2)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [18]:
import numpy as np

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [20]:
import numpy as np

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.hstack((arr1, arr2))

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [160]:
import numpy as np
from numpy import random

arr = np.arange(10,28)
arr2d = random.randint(1,50, size=(4, 4))
arr3d = np.ones((2,3,4))

print(arr[::2], ",",arr2d, ",", arr3d)

[10 12 14 16 18 20 22 24 26] , [[39 14 48 22]
 [43  8 13 32]
 [28 11 27 37]
 [37 15 24  7]] , [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [276]:
import numpy as np
from numpy import random

arr = np.arange(10,28)
arr2d = random.randint(1,50, size=(4, 4))
arr3d = np.ones((2,3,4))

Rarr = arr.reshape(2,9)
Earr2d = arr2d[2:4, (0,1,2,3)]
Negativearr3d = arr3d * -1

print(Rarr, ",",Earr2d, ",", Negativearr3d)

[[10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]] , [[49 41 26 20]
 [ 3 36 43 43]] , [[[-1. -1. -1. -1.]
  [-1. -1. -1. -1.]
  [-1. -1. -1. -1.]]

 [[-1. -1. -1. -1.]
  [-1. -1. -1. -1.]
  [-1. -1. -1. -1.]]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [304]:
import numpy as np
from numpy import random

arr = random.randint(1,50, size=(4, 4))

Marr = np.mean(arr)

Sarr = np.sum(arr)

Minarr = np.min(arr)

Maxarr = np.max(arr)

print(Marr,",",Sarr,",",Minarr,",",Maxarr)

20.75 , 332 , 1 , 48


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [ ]:
import numpy as np
from numpy import random

arr = random.rand(10,10)

minarr = np.min(arr, axis=0)

indarr = np.argsort(arr.flatten())[-5:]

largestarr = np.unravel_index(indarr, arr.shape)


print(arr, ",", minarr, ",", largestarr[0], largestarr[1])


[[0.95615485 0.69196568 0.50179064 0.90266835 0.40898321 0.41918731
  0.49567042 0.82695301 0.56675748 0.75327465]
 [0.86761306 0.7122036  0.54457475 0.790403   0.62515087 0.35524821
  0.45336744 0.08428004 0.77434647 0.90498505]
 [0.40447166 0.45492119 0.22195676 0.92403719 0.64544266 0.29582734
  0.8985506  0.33859031 0.63421246 0.80128894]
 [0.93561554 0.48737992 0.48198877 0.56662101 0.33581109 0.04450111
  0.09248433 0.40163793 0.72101478 0.60659194]
 [0.77781234 0.54737849 0.16724677 0.93440834 0.71129208 0.54652683
  0.93438538 0.66584896 0.39870287 0.46275597]
 [0.48031826 0.77285886 0.95966167 0.60861713 0.50415313 0.90804846
  0.47308706 0.76821831 0.01488809 0.39532129]
 [0.33360084 0.04658338 0.93241656 0.26180687 0.93826823 0.10946405
  0.98808617 0.1483416  0.56089549 0.28276099]
 [0.22496672 0.67035988 0.4439263  0.38650057 0.28542818 0.57722611
  0.34139971 0.39669573 0.70300333 0.9702874 ]
 [0.67322327 0.35636664 0.03658247 0.75575004 0.8241001  0.75541224
  0.45736944